import { Palette } from "std-widgets.slint";
export component LanguageSelector {
    in-out property <bool> french-selected: false;
    callback language_changed(bool);

    en_rect := Rectangle {
        x: 0;
        width: parent.width / 2;
        border-bottom-left-radius: parent.height / 3;
        border-top-left-radius: parent.height / 3;
        background: Palette.alternate-background;
    }

    fr_rect := Rectangle {
        x: parent.width / 2 - 1px;
        width: parent.width / 2;
        border-bottom-right-radius: parent.height / 3;
        border-top-right-radius: parent.height / 3;
        background: Palette.alternate-background;
    }

    // Selection rectangle
    sel_rect := Rectangle {
        background: Palette.selection-background;
        width: parent.width / 2;
        x: french-selected ? parent.width / 2 - 1px : 0;
        border-bottom-left-radius: french-selected ? 0px : parent.height / 3;
        border-top-left-radius: french-selected ? 0px : parent.height / 3;
        border-bottom-right-radius: !french-selected ? 0px : parent.height / 3;
        border-top-right-radius: !french-selected ? 0px : parent.height / 3;
        animate x, border-bottom-left-radius, border-top-left-radius, border-bottom-right-radius, border-top-right-radius { duration: 100ms; }
    }

    Text {
        text: "EN";
        width: parent.width / 2;
        x: 0;
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    Text {
        text: "FR";
        width: parent.width / 2;
        x: parent.width / 2 - 1px;
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    // Border rectangle
    border-rect := Rectangle {
        width: parent.width;
        border-radius: parent.height / 3;
        border-width: 1px;
        border-color: Palette.border;
    }

    FocusScope {
        focus-gained(reason) => {
            border-rect.border-color = Palette.foreground;
        }
        focus-lost(reason) => {
            border-rect.border-color = Palette.border;
        }
        focus-on-tab-navigation: true;
        accessible-role: switch;
        accessible-label: @tr("Language Toggle");
        capture-key-pressed(event) => {
            if (event.text == " " || event.text == "\n") {
                touch.clicked();
                return EventResult.accept;
            } else {
                return EventResult.reject;
            }
        }
    }

    touch := TouchArea {
        width: parent.width;
        height: parent.height;
        clicked => {
            french-selected = !french-selected;
            language_changed(french-selected)
        }
    }
}
