import { Palette } from "std-widgets.slint";
export component ToggleSelector {
    in-out property <bool> toggle-active: false;
    callback toggled(bool);
    in-out property <string> left-title;
    in-out property <string> right-title;

    en_rect := Rectangle {
        x: 0;
        width: parent.width / 2;
        border-bottom-left-radius: parent.height / 3;
        border-top-left-radius: parent.height / 3;
        background: Palette.alternate-background;
    }

    fr_rect := Rectangle {
        x: parent.width / 2 - 1px;
        width: parent.width / 2;
        border-bottom-right-radius: parent.height / 3;
        border-top-right-radius: parent.height / 3;
        background: Palette.alternate-background;
    }

    // Selection rectangle
    sel_rect := Rectangle {
        background: Palette.selection-background;
        width: parent.width / 2;
        x: toggle-active ? parent.width / 2 - 1px : 0;
        border-bottom-left-radius: toggle-active ? 0px : parent.height / 3;
        border-top-left-radius: toggle-active ? 0px : parent.height / 3;
        border-bottom-right-radius: !toggle-active ? 0px : parent.height / 3;
        border-top-right-radius: !toggle-active ? 0px : parent.height / 3;
        animate x, border-bottom-left-radius, border-top-left-radius, border-bottom-right-radius, border-top-right-radius { duration: 100ms; }
    }

    Text {
        text: left-title;
        width: parent.width / 2;
        x: 0;
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    Text {
        text: right-title;
        width: parent.width / 2;
        x: parent.width / 2 - 1px;
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    // Border rectangle
    border-rect := Rectangle {
        width: parent.width;
        border-radius: parent.height / 3;
        border-width: 1px;
        border-color: Palette.border;
    }

    FocusScope {
        focus-gained(reason) => {
            border-rect.border-color = Palette.foreground;
        }
        focus-lost(reason) => {
            border-rect.border-color = Palette.border;
        }
        focus-on-tab-navigation: true;
        accessible-role: switch;
        accessible-label: @tr("Language Toggle");
        capture-key-pressed(event) => {
            if (event.text == " " || event.text == "\n") {
                touch.clicked();
                return EventResult.accept;
            } else {
                return EventResult.reject;
            }
        }
    }

    touch := TouchArea {
        width: parent.width;
        height: parent.height;
        clicked => {
            toggle-active = !toggle-active;
            toggled(toggle-active)
        }
    }
}
