import { TabBase } from "tab_base.slint";
import {
    Button,
    GridBox,
    ScrollView,
    ComboBox,
    TextEdit,
    LineEdit,
    Palette,
    CheckBox,
} from "std-widgets.slint";
import {
    TableDataSlint,
    TableColumnSlint,
    TableColumnTypeSlint,
    TestTableData,
} from "../tabledata.slint";
import { AppStateSlint, AppStateCallbacks } from "../appstate.slint";
import { TinyTickbox } from "../widgets/tiny-tickbox.slint";
import { GridTextbox } from "../widgets/grid-textbox.slint";

export struct CheckResultSlint { ok: bool, x: int, y: int}
export global CSVGlobal {
    out property <length> cell-width: 140px;
    out property <length> cell-height: 20px;
    out property <length> checkbox-size: cell-height * 0.7;
    in-out property <TableDataSlint> data-table;
    callback get-mutated-excluded-rows([int], bool, int) -> [int];
    callback import-csv() -> TableDataSlint;
    pure callback table-contains([int], int) -> bool;
    pure callback check-all-columns-set(TableDataSlint) -> CheckResultSlint;
    pure callback check-all-cells-have-value(TableDataSlint) -> CheckResultSlint;
    pure callback check-numerical-check(TableDataSlint) -> CheckResultSlint;
    pure callback check-table-empty(TableDataSlint) -> CheckResultSlint;
    pure callback save-table(TableDataSlint, string);
}

export component CSVEditor inherits TabBase {
    in-out property <AppStateSlint> data;

    private property <int> error_x: -1;
    private property <int> error_y: -1;

    callback reset-to-here();
    changed data => {
        reset-to-here()
    }

    // Save with no activity for a period of time
    save-timer := Timer {
        interval: 1s;
        running: false;
        triggered => {
            CSVGlobal.save-table(CSVGlobal.data-table, data.save-file-path);
            self.stop();
        }
    }

    function start-save-timer() {
        save-timer.start();
        save-timer.restart();
    }

    function set-check-continue-button-enabled() -> bool {
        let all-columns-set = CSVGlobal.check-all-columns-set(CSVGlobal.data-table);
        let all-cells-have-value = CSVGlobal.check-all-cells-have-value(CSVGlobal.data-table);
        let numerical-check = CSVGlobal.check-numerical-check(CSVGlobal.data-table);
        let empty-check = CSVGlobal.check-table-empty(CSVGlobal.data-table);
        if (!all-columns-set.ok) {
            error_x = all-columns-set.x;
            error_y = all-columns-set.y;
        } else if (!all-cells-have-value.ok) {
            error_x = all-cells-have-value.x;
            error_y = all-cells-have-value.y;
        } else if (!numerical-check.ok) {
            error_x = numerical-check.x;
            error_y = numerical-check.y;
        } else if (!empty-check.ok) {
            error_x = -1;
            error_y = -1;
        } else {
            error_x = -1;
            error_y = -1;
        }
        all-columns-set.ok && all-cells-have-value.ok && numerical-check.ok && empty-check.ok;
    }

    pure function get-error-text() -> string {
        if (!CSVGlobal.check-all-columns-set(CSVGlobal.data-table).ok) {
            return @tr("Cannot continue, not all enabled columns have their types or names set");
        }
        if (!CSVGlobal.check-all-cells-have-value(CSVGlobal.data-table).ok) {
            return @tr("Cannot continue, at least one enabled cell is missing a value");
        }
        if (!CSVGlobal.check-numerical-check(CSVGlobal.data-table).ok) {
            return @tr("Cannot continue, enabled column marked numerical contains categorical data");
        }
        if (!CSVGlobal.check-table-empty(CSVGlobal.data-table).ok) {
            return @tr("Cannot continue, table is empty");
        }
        return "";
    }

    private property <bool> check-continue-button-enabled: false;

    VerticalLayout {
        padding-bottom: 10px;
        padding-left: 4px;
        padding-right: 4px;
        editor := ScrollView {
            viewport-width: (CSVGlobal.data-table.columns.length + 1) * CSVGlobal.cell-width;
            viewport-height: (CSVGlobal.data-table.number-rows + 2) * CSVGlobal.cell-height;
            has-focus: false;
            mouse-drag-pan-enabled: true;

            for i in CSVGlobal.data-table.number-rows: TinyTickbox {
                x: CSVGlobal.checkbox-size * 0.25;
                y: (i + 2.2) * CSVGlobal.cell-height + (CSVGlobal.cell-height - CSVGlobal.checkbox-size) / 2;
                size: CSVGlobal.checkbox-size;
                checked: !CSVGlobal.table-contains(CSVGlobal.data-table.excluded-rows, i);
                on-toggled(checked) => {
                    CSVGlobal.data-table.excluded-rows = CSVGlobal.get-mutated-excluded-rows(CSVGlobal.data-table.excluded-rows, checked, i);
                    start-save-timer();
                    error-text.text = get-error-text();
                    check-continue-button-enabled = set-check-continue-button-enabled();
                    reset-to-here()
                }
            }

            for column[column_index] in CSVGlobal.data-table.columns: Rectangle {
                width: CSVGlobal.cell-width;
                height: CSVGlobal.cell-height * 2;
                x: CSVGlobal.cell-width * column-index + 1.5 * CSVGlobal.checkbox-size;
                y: 0;

                border-color: Palette.border;
                border-width: 0.5px;

                VerticalLayout {
                    h-layout := HorizontalLayout {
                        x: parent.width * 0.05;
                        width: parent.width * 0.9;
                        GridTextbox {
                            text: column.title;
                            text-colour: CSVGlobal.data-table.columns[column-index].enabled ? Palette.foreground : Palette.foreground.transparentize(0.5);
                            width: CSVGlobal.cell-width * 0.8;
                            height: CSVGlobal.cell-height;
                            read-only: !CSVGlobal.data-table.columns[column-index].enabled;
                            on-edit(new-text) => {
                                column.title = new-text;
                                CSVGlobal.data-table.columns[column-index].title = new-text;
                                self.text = new-text;
                                start-save-timer();
                                error-text.text = get-error-text();
                                check-continue-button-enabled = set-check-continue-button-enabled();
                                reset-to-here()
                            }
                        }

                        Rectangle {
                            horizontal-stretch: 1;
                        }

                        TinyTickbox {
                            size: CSVGlobal.checkbox-size;
                            checked: CSVGlobal.data-table.columns[column-index].enabled;
                            y: (parent.height - self.size) / 2;
                            on-toggled(checked) => {
                                CSVGlobal.data-table.columns[column-index].enabled = checked;
                                start-save-timer();
                                error-text.text = get-error-text();
                                check-continue-button-enabled = set-check-continue-button-enabled();
                                reset-to-here()
                            }
                        }
                    }

                    pure function column-type-to-string(type: TableColumnTypeSlint) -> string {
                        if (type == TableColumnTypeSlint.Numerical) {
                            return @tr("Numerical");
                        }
                        if (type == TableColumnTypeSlint.Categorical) {
                            return @tr("Categorical");
                        }
                        return @tr("Unset");
                    }

                    ComboBox {
                        enabled: CSVGlobal.data-table.columns[column-index].enabled;
                        x: parent.width * 0.05;
                        width: parent.width * 0.9;
                        height: CSVGlobal.cell-height;
                        model: [@tr("Unset"), @tr("Numerical"), @tr("Categorical")];
                        current-value: column-type-to-string(CSVGlobal.data-table.columns[column-index].column_type);
                        selected(current-value) => {
                            if (current-value == @tr("Unset")) {
                                CSVGlobal.data-table.columns[column-index].column_type = TableColumnTypeSlint.Unset;
                            } else if (current-value == @tr("Numerical")) {
                                CSVGlobal.data-table.columns[column-index].column_type = TableColumnTypeSlint.Numerical;
                            } else if (current-value == @tr("Categorical")) {
                                CSVGlobal.data-table.columns[column-index].column_type = TableColumnTypeSlint.Categorical;
                            }
                            start-save-timer();
                            error-text.text = get-error-text();
                            check-continue-button-enabled = set-check-continue-button-enabled();
                            reset-to-here()
                        }
                    }
                }

                Rectangle {
                    border-radius: 3px;
                    border-width: 1px;
                    border-color: error_y == -1 && error_x == column-index ? orangered : transparent;
                    x: parent.width * 0.05;
                    height: 2 * CSVGlobal.cell-height;
                    width: parent.width * 0.9;
                }

                for column-entry[row_index] in column.column-entries: Rectangle {
                    width: CSVGlobal.cell-width;
                    height: CSVGlobal.cell-height;
                    y: (row-index + 2.2) * CSVGlobal.cell-height;
                    border-width: 0.5px;
                    border-color: error_x == column-index && error_y == row-index && CSVGlobal.data-table.columns[column-index].enabled && !CSVGlobal.table-contains(CSVGlobal.data-table.excluded-rows, row-index) ? red : Palette.border;
                    pure function get_text_colour() -> brush {
                        if (!CSVGlobal.data-table.columns[column-index].enabled || CSVGlobal.table-contains(CSVGlobal.data-table.excluded-rows, row_index)) {
                            return Palette.foreground.transparentize(0.5);
                        } else {
                            return Palette.foreground;
                        }
                    }
                    GridTextbox {
                        text: column-entry;
                        text-colour: get_text_colour();
                        read-only: !CSVGlobal.data-table.columns[column-index].enabled || CSVGlobal.table-contains(CSVGlobal.data-table.excluded-rows, row_index);
                        on-edit(t) => {
                            CSVGlobal.data-table.columns[column-index].column-entries[row-index] = t;
                            start-save-timer();
                            error-text.text = get-error-text();
                            check-continue-button-enabled = set-check-continue-button-enabled();
                            reset-to-here()
                        }
                    }
                }
            }
        }

        HorizontalLayout {
            height: 36px;
            spacing: 3px;
            Button {
                text: @tr("Import New CSV");
                clicked => {
                    CSVGlobal.data-table = CSVGlobal.import-csv();
                    start-save-timer();
                    error-text.text = get-error-text();
                    check-continue-button-enabled = set-check-continue-button-enabled();
                    reset-to-here()
                }
            }

            error-text := Text {
                text: get-error-text();
                horizontal-stretch: 1;
                horizontal-alignment: center;
                vertical-alignment: center;
            }

            Button {
                text: @tr("Continue");
                enabled: check-continue-button-enabled;
                init => {
                    check-continue-button-enabled = set-check-continue-button-enabled()
                }
                clicked => {
                    CSVGlobal.save-table(CSVGlobal.data-table, data.save-file-path);
                    root.next()
                }
            }
        }
    }
}
