import { TabBase } from "tab_base.slint";
import {
    Button,
    GridBox,
    ScrollView,
    ComboBox,
    TextEdit,
    LineEdit,
    Palette,
    CheckBox,
} from "std-widgets.slint";
import {
    TableDataSlint,
    TableColumnSlint,
    TableColumnTypeSlint,
    TestTableData,
} from "../tabledata.slint";
import { TinyTickbox } from "../widgets/tiny-tickbox.slint";
import { MultilineTooltip } from "../widgets/multiline-tooltip.slint";
import { GridTextbox } from "../widgets/grid-textbox.slint";

export global CSVGlobal {
    out property <length> cell-width: 140px;
    out property <length> cell-height: 20px;
    out property <length> checkbox-size: cell-height * 0.7;
    in-out property <TableDataSlint> data-table: TestTableData.data;
    callback get-mutated-excluded-rows([int], bool, int) -> [int];
    callback import-csv() -> TableDataSlint;
    pure callback table-contains([int], int) -> bool;
}

export component CSVEditor inherits TabBase {
    VerticalLayout {
        editor := ScrollView {
            viewport-width: CSVGlobal.data-table.columns.length * CSVGlobal.cell-width;
            viewport-height: (CSVGlobal.data-table.number-rows + 2) * CSVGlobal.cell-height;
            has-focus: false;
            mouse-drag-pan-enabled: true;

            for i in CSVGlobal.data-table.number-rows: TinyTickbox {
                x: CSVGlobal.checkbox-size * 0.25;
                y: (i + 2.2) * CSVGlobal.cell-height + (CSVGlobal.cell-height - CSVGlobal.checkbox-size) / 2;
                size: CSVGlobal.checkbox-size;
                checked: !CSVGlobal.table-contains(CSVGlobal.data-table.excluded-rows, i);
                on-toggled(checked) => {
                    CSVGlobal.data-table.excluded-rows = CSVGlobal.get-mutated-excluded-rows(CSVGlobal.data-table.excluded-rows, checked, i);
                }
            }

            for column[column_index] in CSVGlobal.data-table.columns: Rectangle {
                width: CSVGlobal.cell-width;
                height: CSVGlobal.cell-height * 2;
                x: CSVGlobal.cell-width * column-index + 1.5 * CSVGlobal.checkbox-size;
                y: 0;

                border-color: Palette.border;
                border-width: 0.5px;

                VerticalLayout {
                    h-layout := HorizontalLayout {
                        x: parent.width * 0.05;
                        width: parent.width * 0.9;
                        Text {
                            text: column.title;
                            color: CSVGlobal.data-table.columns[column-index].enabled ? Palette.foreground : Palette.foreground.transparentize(0.5);
                            horizontal-alignment: left;
                            vertical-alignment: center;
                            width: CSVGlobal.cell-width * 0.8;
                            height: CSVGlobal.cell-height;
                            overflow: TextOverflow.elide;
                            MultilineTooltip {
                                width: parent.width;
                                height: parent.height;
                                popup-width: h-layout.width;
                                text: column.title;
                                hover-duration: 700ms;
                            }
                        }

                        Rectangle {
                            horizontal-stretch: 1;
                        }

                        TinyTickbox {
                            size: CSVGlobal.checkbox-size;
                            checked: CSVGlobal.data-table.columns[column-index].enabled;
                            y: (parent.height - self.size) / 2;
                            on-toggled(checked) => {
                                CSVGlobal.data-table.columns[column-index].enabled = checked;
                            }
                        }
                    }

                    ComboBox {
                        enabled: CSVGlobal.data-table.columns[column-index].enabled;
                        width: parent.width * 0.9;
                        x: parent.width * 0.05;
                        height: CSVGlobal.cell-height;
                        model: [@tr("Unset"), @tr("Numerical"), @tr("Categorical")];
                        selected(current-value) => {
                            if (current-value == @tr("Unset")) {
                                CSVGlobal.data-table.columns[column-index].column_type = TableColumnTypeSlint.Unset;
                            } else if (current-value == @tr("Numerical")) {
                                CSVGlobal.data-table.columns[column-index].column_type = TableColumnTypeSlint.Numerical;
                            } else if (current-value == @tr("Categorical")) {
                                CSVGlobal.data-table.columns[column-index].column_type = TableColumnTypeSlint.Categorical;
                            }
                        }
                    }
                }

                for column-entry[row_index] in column.column-entries: Rectangle {
                    width: CSVGlobal.cell-width;
                    height: CSVGlobal.cell-height;
                    y: (row-index + 2.2) * CSVGlobal.cell-height;
                    border-width: 0.5px;
                    border-color: Palette.border;
                    pure function get_text_colour() -> brush {
                        if (!CSVGlobal.data-table.columns[column-index].enabled || CSVGlobal.table-contains(CSVGlobal.data-table.excluded-rows, row_index)) {
                            return Palette.foreground.transparentize(0.5);
                        } else {
                            return Palette.foreground;
                        }
                    }
                    GridTextbox {
                        text: column-entry;
                        text-colour: get_text_colour();
                        read-only: !CSVGlobal.data-table.columns[column-index].enabled || CSVGlobal.table-contains(CSVGlobal.data-table.excluded-rows, row_index);
                        on-edit(t) => {
                            CSVGlobal.data-table.columns[column-index].column-entries[row-index] = t;
                        }
                    }
                }
            }
        }

        HorizontalLayout {
            height: 36px;
            Button {
                text: @tr("Import CSV");
                clicked => {
                    CSVGlobal.data-table = CSVGlobal.import-csv();
                }
            }

            Rectangle {
                horizontal-stretch: 1;
            }

            Button {
                text: @tr("Continue");
            }
        }
    }
}
