import { Button, LineEdit } from "std-widgets.slint";
import { TabBase } from "tab_base.slint";
import { AppStateSlint } from "../appstate.slint";
import { LanguageSelector } from "../widgets/language-selector.slint";
export component ProjectSetup inherits TabBase {
    callback file-browser(create-new: bool);
    in-out property <AppStateSlint> data;
    callback language_changed(bool);

    VerticalLayout {
        padding-left: 40px;
        spacing: 10px;
        HorizontalLayout {
            padding-top: 20px;
            spacing: 10px;
            Text {
                text: @tr("Project File Path:");
                vertical-alignment: center;
            }

            LineEdit {
                y: 0;
                text: data.save-file-path;
                accepted(text) => {
                    data.save-file-path = text;
                }
            }

            Rectangle {
                horizontal-stretch: 1;
            }
        }

        HorizontalLayout {
            spacing: 4px;
            Button {
                text: @tr("Open File");
                horizontal-stretch: 1;
                clicked => {
                    file-browser(false)
                }
            }

            Button {
                text: @tr("New Project");
                horizontal-stretch: 1;
                clicked => {
                    file-browser(true)
                }
            }

            Rectangle {
                horizontal-stretch: 8;
            }
        }

        // Next button and language toggle
        Rectangle {
            vertical-stretch: 1;
        }

        HorizontalLayout {
            padding: 8px;
            height: 48px;

            LanguageSelector {
                width: 80px;
                french-selected: data.french-selected;
                language_changed(fr) => {
                    language_changed(fr)
                }
            }

            Rectangle {
                horizontal-stretch: 1;
            }

            btn := Button {
                text: @tr("Next");
                enabled: false;

                clicked => {
                    root.next()
                }
            }
        }
    }
}
