import { Button, LineEdit } from "std-widgets.slint";
import { TabBase } from "tab_base.slint";
import { AppStateSlint, AppStateCallbacks } from "../appstate.slint";
import { LanguageSelector } from "../widgets/language-selector.slint";

export global SetupCallbacks {
    callback language_changed(bool);
    callback file-browser(create-new: bool);
    callback setup-next-button() -> string;
}

export component ProjectSetup inherits TabBase {
    in-out property <AppStateSlint> data;

    VerticalLayout {
        padding-left: 40px;
        spacing: 10px;
        HorizontalLayout {
            padding-top: 20px;
            spacing: 10px;
            Text {
                text: @tr("Project File Path:");
                vertical-alignment: center;
            }

            LineEdit {
                y: 0;
                text: data.save-file-path;
                accepted(text) => {
                    data.save-file-path = text;
                    AppStateCallbacks.sync-appstate(data)
                }
            }

            Rectangle {
                horizontal-stretch: 1;
            }
        }

        HorizontalLayout {
            spacing: 4px;
            Button {
                text: @tr("Open File");
                horizontal-stretch: 1;
                clicked => {
                    SetupCallbacks.file-browser(false)
                }
            }

            Button {
                text: @tr("New Project");
                horizontal-stretch: 1;
                clicked => {
                    SetupCallbacks.file-browser(true)
                }
            }

            Rectangle {
                horizontal-stretch: 8;
            }
        }

        // Next button and language toggle
        Rectangle {
            vertical-stretch: 1;
        }

        HorizontalLayout {
            padding: 8px;
            height: 48px;

            LanguageSelector {
                width: 80px;
                french-selected: data.french-selected;
                language_changed(fr) => {
                    SetupCallbacks.language_changed(fr)
                }
            }

            Rectangle {
                horizontal-stretch: 1;
            }

            msg := Text {
                color: red;
            }

            btn := Button {
                text: @tr("Next");
                enabled: !data.save-file-path.is-empty;

                clicked => {
                    let result = SetupCallbacks.setup-next-button();
                    if (result == "yay") {
                        root.next()
                    } else {
                        msg.text = @tr("Cannot continue: {}", result);
                        msg.visible = true;
                    }
                }
            }
        }
    }
}
