import { Button, VerticalBox, TabWidget, Palette } from "std-widgets.slint";
import { TabsWidget } from "widgets/tabs-widget.slint";
import { CSVEditor, CSVGlobal } from "tabs/csv_editor.slint";
import { ProjectSetup } from "tabs/setup.slint";
import { AppStateSlint } from "appstate.slint";
import { Configuration, ConfigurationGlobal } from "tabs/configuration.slint";
import { Results, ResultsGlobal } from "tabs/results.slint";

export { AppStateCallbacks } from "appstate.slint";
export { SetupCallbacks } from "tabs/setup.slint";
export { CSVGlobal } from "tabs/csv_editor.slint";
export { ConfigurationGlobal, ScoredRegressionEntrySlint } from "tabs/configuration.slint";
export { ResultsGlobal } from "tabs/results.slint";

export component AppWindow inherits Window {
    min-width: 600px;
    min-height: 400px;
    default-font-size: 12px;
    title: "Beeswarmer";

    callback reset-data(idx: int);

    in-out property <AppStateSlint> app-data-slint;

    public function call-csv-save() {
        CSVGlobal.save-table(CSVGlobal.data-table, app-data-slint.save-file-path);
    }

    public function sync-theme() {
        Palette.color-scheme = app-data-slint.dark-selected ? ColorScheme.dark : ColorScheme.light;
    }

    VerticalLayout {
        tab := TabsWidget {
            height: 40px;
            tab-titles: [@tr("Project Setup"), @tr("CSV Editor"), @tr("Configuration"), @tr("Results")];
            highest-achieved: 0;
        }

        function general-next(tab_idx: int) {
            tab.selected-index += 1;
            tab.highest-achieved = tab_idx + 1;
        }
        function general-reset(idx: int) {
            tab.selected-index = idx;
            tab.highest-achieved = idx;
        }

        if tab.selected-index == 0: ProjectSetup {
            font-size: root.default-font-size;
            window-width: root.width;
            data <=> app-data-slint;
            reset-to-here() => {
                general-reset(0);
            }
            next => general-next(0);
        }
        if tab.selected-index == 1: CSVEditor {
            font-size: root.default-font-size;
            window-width: root.width;
            data <=> app-data-slint;
            reset-to-here() => {
                general-reset(1);
                ConfigurationGlobal.save-simple-selected("Unset");
                ConfigurationGlobal.save-scored-regression-entries([]);
                ConfigurationGlobal.save-binary-selected("Unset");
            }
            next => general-next(1);
        }

        if tab.selected-index == 2: Configuration {
            font-size: root.default-font-size;
            window-width: root.width;
            data <=> app-data-slint;
            reset-to-here() => {
                general-reset(2);
            }
            next => general-next(2);
        }

        if tab.selected-index == 3: Results {
            font-size: root.default-font-size;
            window-width: root.width;
            data: app-data-slint;
        }
    }
}
